apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
    ports:
     - port: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
      app: mysql
  spec:
    accessModes:
      - ReadWriteOnce:
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: Deployment
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    containers:
     - image: mymysql
       name: mysql
       env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
       ports:
        - containerPort: 3306
          name: mysql
       VolumeMounts:
        - name: mysql-pst
          mountPath: /var/lib/mysql
    volumes:
     - name: mysql-pst
       persistentVolumeClaim:
           claimName: mysql-pv-claim