apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: http
      port: 80
    - protocol: TCP
      name: https
      port: 443
---
apiVersion: v1
kind: Service
metadata:
   name: nginxss
   labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 1234
    nodePort: 1234
    protocol: TCP
    name: ssh
  - port: 1234
 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mynginx:latest
        imagePullPolicy: Never
        ports:
         - containerPort: 80
         - containerPort: 443