apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress-app
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wordpress-pv-claim
    labels:
        app: wordpress
    spec:
        accessModes:
          - ReadWriteOnce
        resources:
         requests:
          storage: 1Gi 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: mywordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
